import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="border flex justify-center">
          <Link href={'/'}>
            <div className="px-4 mx-2 border my-4 py-2">
              Home
            </div>
          </Link>
          <Link href={'/user'}><div className="px-4 mx-2 border my-4 py-2">
            User
          </div></Link>
        </div>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
