import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, UserButton } from "@clerk/nextjs";
import Link from "next/link";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ecomx",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div>
            <div className="bg-gradient-to-r from-blue-500 to-purple-500 h-16 flex items-center justify-center px-4">
              <h1 className="text-white text-2xl font-bold">Welcome to ecomx</h1>
              <div className="flex items-center ml-auto">
                <Link href="/" className="text-white ml-4">Home</Link>
                <Link href="/login" className="text-white ml-4">Login</Link>
                <Link href="/register" className="text-white ml-4">Register</Link>
                <Link href="/dashboard" className="text-white ml-4">Dashboard</Link>
                <Link href="/user-profile" className="text-white ml-4">Profile</Link>
                <div className="px-4">
                  <UserButton />
                </div>
              </div>
            </div>
          </div>
          <div className="">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
